name: binder-stress
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - numba
  - pandas
  - scikit-learn
  - ipywidgets
  - jupyterlab
  - pip
  - pip:
      - tqdm
